// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/securitypolicykeyword"
)

// SecurityPolicyKeywordDelete is the builder for deleting a SecurityPolicyKeyword entity.
type SecurityPolicyKeywordDelete struct {
	config
	hooks    []Hook
	mutation *SecurityPolicyKeywordMutation
}

// Where appends a list predicates to the SecurityPolicyKeywordDelete builder.
func (_d *SecurityPolicyKeywordDelete) Where(ps ...predicate.SecurityPolicyKeyword) *SecurityPolicyKeywordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SecurityPolicyKeywordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SecurityPolicyKeywordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SecurityPolicyKeywordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(securitypolicykeyword.Table, sqlgraph.NewFieldSpec(securitypolicykeyword.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SecurityPolicyKeywordDeleteOne is the builder for deleting a single SecurityPolicyKeyword entity.
type SecurityPolicyKeywordDeleteOne struct {
	_d *SecurityPolicyKeywordDelete
}

// Where appends a list predicates to the SecurityPolicyKeywordDelete builder.
func (_d *SecurityPolicyKeywordDeleteOne) Where(ps ...predicate.SecurityPolicyKeyword) *SecurityPolicyKeywordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SecurityPolicyKeywordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{securitypolicykeyword.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SecurityPolicyKeywordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
