// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/securitypolicykeyword"
)

// SecurityPolicyKeywordUpdate is the builder for updating SecurityPolicyKeyword entities.
type SecurityPolicyKeywordUpdate struct {
	config
	hooks    []Hook
	mutation *SecurityPolicyKeywordMutation
}

// Where appends a list predicates to the SecurityPolicyKeywordUpdate builder.
func (_u *SecurityPolicyKeywordUpdate) Where(ps ...predicate.SecurityPolicyKeyword) *SecurityPolicyKeywordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SecurityPolicyKeywordUpdate) SetUpdatedAt(v time.Time) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SecurityPolicyKeywordUpdate) SetDeletedAt(v time.Time) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdate) SetNillableDeletedAt(v *time.Time) *SecurityPolicyKeywordUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SecurityPolicyKeywordUpdate) ClearDeletedAt() *SecurityPolicyKeywordUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SecurityPolicyKeywordUpdate) SetGroupID(v int64) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdate) SetNillableGroupID(v *int64) *SecurityPolicyKeywordUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SecurityPolicyKeywordUpdate) ClearGroupID() *SecurityPolicyKeywordUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *SecurityPolicyKeywordUpdate) SetKeyword(v string) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdate) SetNillableKeyword(v *string) *SecurityPolicyKeywordUpdate {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SecurityPolicyKeywordUpdate) SetCategory(v string) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdate) SetNillableCategory(v *string) *SecurityPolicyKeywordUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SecurityPolicyKeywordUpdate) SetEnabled(v bool) *SecurityPolicyKeywordUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdate) SetNillableEnabled(v *bool) *SecurityPolicyKeywordUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SecurityPolicyKeywordUpdate) SetGroup(v *Group) *SecurityPolicyKeywordUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SecurityPolicyKeywordMutation object of the builder.
func (_u *SecurityPolicyKeywordUpdate) Mutation() *SecurityPolicyKeywordMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SecurityPolicyKeywordUpdate) ClearGroup() *SecurityPolicyKeywordUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecurityPolicyKeywordUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityPolicyKeywordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecurityPolicyKeywordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityPolicyKeywordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SecurityPolicyKeywordUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if securitypolicykeyword.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized securitypolicykeyword.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := securitypolicykeyword.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityPolicyKeywordUpdate) check() error {
	if v, ok := _u.mutation.Keyword(); ok {
		if err := securitypolicykeyword.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "SecurityPolicyKeyword.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := securitypolicykeyword.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SecurityPolicyKeyword.category": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityPolicyKeywordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securitypolicykeyword.Table, securitypolicykeyword.Columns, sqlgraph.NewFieldSpec(securitypolicykeyword.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(securitypolicykeyword.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(securitypolicykeyword.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(securitypolicykeyword.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(securitypolicykeyword.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(securitypolicykeyword.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(securitypolicykeyword.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   securitypolicykeyword.GroupTable,
			Columns: []string{securitypolicykeyword.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   securitypolicykeyword.GroupTable,
			Columns: []string{securitypolicykeyword.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securitypolicykeyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecurityPolicyKeywordUpdateOne is the builder for updating a single SecurityPolicyKeyword entity.
type SecurityPolicyKeywordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecurityPolicyKeywordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetUpdatedAt(v time.Time) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetDeletedAt(v time.Time) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdateOne) SetNillableDeletedAt(v *time.Time) *SecurityPolicyKeywordUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SecurityPolicyKeywordUpdateOne) ClearDeletedAt() *SecurityPolicyKeywordUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetGroupID(v int64) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdateOne) SetNillableGroupID(v *int64) *SecurityPolicyKeywordUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SecurityPolicyKeywordUpdateOne) ClearGroupID() *SecurityPolicyKeywordUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetKeyword(v string) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdateOne) SetNillableKeyword(v *string) *SecurityPolicyKeywordUpdateOne {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetCategory(v string) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdateOne) SetNillableCategory(v *string) *SecurityPolicyKeywordUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SecurityPolicyKeywordUpdateOne) SetEnabled(v bool) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SecurityPolicyKeywordUpdateOne) SetNillableEnabled(v *bool) *SecurityPolicyKeywordUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SecurityPolicyKeywordUpdateOne) SetGroup(v *Group) *SecurityPolicyKeywordUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SecurityPolicyKeywordMutation object of the builder.
func (_u *SecurityPolicyKeywordUpdateOne) Mutation() *SecurityPolicyKeywordMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SecurityPolicyKeywordUpdateOne) ClearGroup() *SecurityPolicyKeywordUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the SecurityPolicyKeywordUpdate builder.
func (_u *SecurityPolicyKeywordUpdateOne) Where(ps ...predicate.SecurityPolicyKeyword) *SecurityPolicyKeywordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecurityPolicyKeywordUpdateOne) Select(field string, fields ...string) *SecurityPolicyKeywordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SecurityPolicyKeyword entity.
func (_u *SecurityPolicyKeywordUpdateOne) Save(ctx context.Context) (*SecurityPolicyKeyword, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityPolicyKeywordUpdateOne) SaveX(ctx context.Context) *SecurityPolicyKeyword {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecurityPolicyKeywordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityPolicyKeywordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SecurityPolicyKeywordUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if securitypolicykeyword.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized securitypolicykeyword.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := securitypolicykeyword.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityPolicyKeywordUpdateOne) check() error {
	if v, ok := _u.mutation.Keyword(); ok {
		if err := securitypolicykeyword.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "SecurityPolicyKeyword.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := securitypolicykeyword.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SecurityPolicyKeyword.category": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityPolicyKeywordUpdateOne) sqlSave(ctx context.Context) (_node *SecurityPolicyKeyword, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securitypolicykeyword.Table, securitypolicykeyword.Columns, sqlgraph.NewFieldSpec(securitypolicykeyword.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecurityPolicyKeyword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securitypolicykeyword.FieldID)
		for _, f := range fields {
			if !securitypolicykeyword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != securitypolicykeyword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(securitypolicykeyword.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(securitypolicykeyword.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(securitypolicykeyword.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(securitypolicykeyword.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(securitypolicykeyword.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(securitypolicykeyword.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   securitypolicykeyword.GroupTable,
			Columns: []string{securitypolicykeyword.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   securitypolicykeyword.GroupTable,
			Columns: []string{securitypolicykeyword.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SecurityPolicyKeyword{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securitypolicykeyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
