// Code generated by ent, DO NOT EDIT.

package securitypolicykeyword

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldDeletedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldGroupID, v))
}

// Keyword applies equality check predicate on the "keyword" field. It's identical to KeywordEQ.
func Keyword(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldKeyword, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldCategory, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotNull(FieldDeletedAt))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotNull(FieldGroupID))
}

// KeywordEQ applies the EQ predicate on the "keyword" field.
func KeywordEQ(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldKeyword, v))
}

// KeywordNEQ applies the NEQ predicate on the "keyword" field.
func KeywordNEQ(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldKeyword, v))
}

// KeywordIn applies the In predicate on the "keyword" field.
func KeywordIn(vs ...string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldKeyword, vs...))
}

// KeywordNotIn applies the NotIn predicate on the "keyword" field.
func KeywordNotIn(vs ...string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldKeyword, vs...))
}

// KeywordGT applies the GT predicate on the "keyword" field.
func KeywordGT(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldKeyword, v))
}

// KeywordGTE applies the GTE predicate on the "keyword" field.
func KeywordGTE(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldKeyword, v))
}

// KeywordLT applies the LT predicate on the "keyword" field.
func KeywordLT(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldKeyword, v))
}

// KeywordLTE applies the LTE predicate on the "keyword" field.
func KeywordLTE(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldKeyword, v))
}

// KeywordContains applies the Contains predicate on the "keyword" field.
func KeywordContains(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldContains(FieldKeyword, v))
}

// KeywordHasPrefix applies the HasPrefix predicate on the "keyword" field.
func KeywordHasPrefix(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldHasPrefix(FieldKeyword, v))
}

// KeywordHasSuffix applies the HasSuffix predicate on the "keyword" field.
func KeywordHasSuffix(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldHasSuffix(FieldKeyword, v))
}

// KeywordEqualFold applies the EqualFold predicate on the "keyword" field.
func KeywordEqualFold(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEqualFold(FieldKeyword, v))
}

// KeywordContainsFold applies the ContainsFold predicate on the "keyword" field.
func KeywordContainsFold(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldContainsFold(FieldKeyword, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldContainsFold(FieldCategory, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.FieldNEQ(FieldEnabled, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecurityPolicyKeyword) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecurityPolicyKeyword) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecurityPolicyKeyword) predicate.SecurityPolicyKeyword {
	return predicate.SecurityPolicyKeyword(sql.NotPredicates(p))
}
